name: Kubernetes Manifest Diff Action
description:
  Compare Kubernetes manifests between git references using helm, kustomize, or
  plain YAML
author: kzap

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: file-plus
  color: blue

# Define your inputs here.
inputs:
  tool:
    description: Tool to use for manifest generation (yaml, helm, kustomize)
    required: false
    default: 'yaml'
  command:
    description:
      Command to execute for manifest generation (defaults based on tool)
    required: false
    default: ''
  base-ref:
    description:
      'Base reference for comparison (default: main or repo default branch)'
    required: false
    default: ''
  head-ref:
    description: 'Head reference for comparison (default: current commit)'
    required: false
    default: ''
  working-dir:
    description: Working directory relative to repo root
    required: false
    default: './'
  head-working-dir:
    description: |
      If the working directory for the files we want to compare is different from the working directory for the base files, specify it here.
      By default, the working directory for the base and head files is the same.
    required: false
    default: ''
  prepare-commands:
    description: |
      Commands to run before generating manifests (one per line).
      These commands are executed in the working directory before running the main command.
      Useful for setup tasks like installing dependencies, updating submodules, etc.
    required: false
    default: ''

# Define your outputs here.
outputs:
  diff-output:
    description: The YAML diff between base and head manifests
  stderr:
    description: Standard error output from failed commands (for debugging)
  error:
    description: Boolean indicating if any command failed (true/false)

runs:
  using: node24
  main: dist/index.js
