name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  actions: read
  checks: read
  deployments: read
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  test-yaml:
    runs-on: ubuntu-latest
    name: Test YAML tool
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test k8s-diff-action with YAML
        uses: ./
        id: yaml-diff
        with:
          tool: yaml
          working-dir: tests/fixtures/yaml
          base-ref: ${{ github.head_ref || github.ref_name }}
          head-ref: ${{ github.sha }}

      - name: Print YAML diff output
        run: |
          echo "Diff output:"
          echo "${{ steps.yaml-diff.outputs.diff-output }}"
          echo "Stderr:"
          echo "${{ steps.yaml-diff.outputs.stderr }}"
          echo "Error: ${{ steps.yaml-diff.outputs.error }}"

  test-helm:
    runs-on: ubuntu-latest
    name: Test Helm tool
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test k8s-diff-action with Helm
        uses: ./
        id: helm-diff
        with:
          tool: helm
          working-dir: tests/fixtures/helm/basic-app
          base-ref: ${{ github.head_ref || github.ref_name }}
          head-ref: ${{ github.sha }}

      - name: Print Helm diff output
        run: |
          echo "Diff output:"
          echo "${{ steps.helm-diff.outputs.diff-output }}"
          echo "Stderr:"
          echo "${{ steps.helm-diff.outputs.stderr }}"
          echo "Error: ${{ steps.helm-diff.outputs.error }}"

  test-custom-command:
    runs-on: ubuntu-latest
    name: Test custom command
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test k8s-diff-action with custom command
        uses: ./
        id: custom-diff
        with:
          tool: helm
          command: helm template my-release .
          working-dir: tests/fixtures/helm/basic-app
          base-ref: ${{ github.head_ref || github.ref_name }}
          head-ref: ${{ github.sha }}

      - name: Print custom command diff output
        run: |
          echo "Diff output:"
          echo "${{ steps.custom-diff.outputs.diff-output }}"
          echo "Stderr:"
          echo "${{ steps.custom-diff.outputs.stderr }}"
          echo "Error: ${{ steps.custom-diff.outputs.error }}"
